config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new(role: 'guest')
    can :read, :all
    if user.is? :admin
      can :manage, :all
    elsif user.is? :default
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :manage, Like, author: user
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :text, presence: true

  after_create :update_comments_counter

  after_destroy do
    post.decrement!(:comments_counter)
  end

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :author_id, uniqueness: { scope: :post_id }

  after_create :update_likes_counter

  after_destroy do
    post.decrement!(:likes_counter)
  end

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  before_create do
    self.likes_counter = 0
    self.comments_counter = 0
    update_posts_counter
  end

  after_destroy do
    author.decrement!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author, :post).order(created_at: :desc).limit(5)
  end

  def liked?(user_id)
    likes.find { |like| like.author_id == user_id }
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  before_create do
    self.posts_counter = 0
  end

  def recent_posts
    posts.includes(:author, :likes, :comments).order(created_at: :desc).limit(3)
  end
  ## CanCan Roles
  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @post = Post.find(params[:post_id])
    @new_comment = Comment.new(comment_params.merge(post_id: @post.id, author_id: current_user.id))
    if @new_comment.save
      flash[:success] = 'Comment was saved'
    else
      flash[:error] = 'Failed to add comment'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Comment was deleted'
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @new_like = Like.new(post: @post, author: @user)
    respond_to do |format|
      format.html do
        if @new_like.save
          flash[:success] = 'Liked Post'
          redirect_back(fallback_location: root_path)
        elsif @post.liked?(@user.id)
          Like.where(author: @user, post: @post).destroy_all
          flash[:success] = 'Unliked Post'
          redirect_back(fallback_location: root_path)
        else
          flash.now[:alert] = 'Error while trying to like post'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :current_user

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments, :likes).order(created_at: :desc)
  end

  def show
    @post_current = Post.find(params[:id])
  end

  def new
    @post_current = Post.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @new_post = @current_user.posts.new(post_params)
    @new_post.likes_counter = 0
    @new_post.comments_counter = 0
    respond_to do |format|
      format.html do
        if @new_post.save
          flash[:success] = 'Post was saved'
          redirect_to user_post_path(user_id: @current_user.id, id: @new_post.id)
        else
          flash[:error] = 'Error: Unable to create post'
          redirect_to new_user_post_path
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:success] = 'Post was deleted'
    redirect_to user_posts_path(post.author.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user_current = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
      <%= render partial: 'shared/flash' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="posts">
  <%= render partial: "shared/back", locals: {back:user_path(id:params[:user_id])} %>
  <%= render partial: "shared/user", locals: {user: @user} %>
  <% @posts.each do |current_post| %>
    <div class="post-item">
      <%= render partial: "shared/post", locals: {post: current_post} %>
      <div class="post-comments container">
        <%= render partial: "shared/comment", collection: current_post.recent_comments %>
        <%= render partial: "shared/comment_form", locals: {user_id: current_post.author_id, post_id: current_post.id} %>
      </div>
    </div>
  <% end %>
  <button class="pagination"><%= link_to "Make a Post", new_user_post_path, class:"link-to_user" %></button>
</section>

app/views/posts/new.html.erb
<%= render partial: "shared/post_form", locals: {new_post: @post_current, current_user_id: @current_user.id } %>

app/views/posts/show.html.erb
<section class="single-post">
  <%= render partial: "shared/back", locals: {back:user_posts_path} %>
  <div class="post-container container">
    <div class="post-container_title">
      <h3 class="post-container_heading"><%= @post_current.title %>
        #<%= @post_current.id %>
        by
        <%= @post_current.author.name %></h3>
      <div class="post-container_stats">

        <p>Comments:
          <%= @post_current.comments_counter %></p>
        <p>Likes:
          <%= @post_current.likes_counter %></p>
        <%= render partial: "shared/like_form", locals: {user_id: params[:user_id], post_id: params[:id]} %>
      </div>
    </div>
    <p class="post-container_text"><%= @post_current.text %></p>
  </div>
  <div class="post-comments container">
    <%= render partial: "shared/comment", collection: @post_current.comments.includes(:author, :post) %>
    <%= render partial: "shared/comment_form", locals: {user_id: params[:user_id],post_id: params[:id]} %>
  </div>
</section>

app/views/shared/_back.html.erb
<%= link_to back, class:"link-back link" do %>
  <i class="fa fa-arrow-left"></i>
<% end %>

app/views/shared/_comment.html.erb
<div class="comment">
  <p><%= comment.author.name %>:
    <span><%= comment.text %></span></p>
  <%= button_to user_post_comment_path(user_id: comment.post.author_id, post_id: comment.post_id, id: comment.id), class:"link", method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
</div>

app/views/shared/_comment_form.html.erb
<%= form_with model:Comment.new,  url: user_post_comments_path(user_id: user_id, post_id:post_id), class: "comment-form", scope: :comment do |form| %>
  <%= form.text_area :text, class:"comment-form_text", placeholder: "Add comment ..." %>
  <%= form.submit "Comment", class: "submit-comment" %>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id =>  "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/shared/_like_form.html.erb
<%= form_with Model: Like.new, url: user_post_likes_path(user_id: user_id,post_id: post_id), class: "like-form", scope: :like do |form| %>
  <%= button_tag type: 'submit', class: "heart" do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/shared/_post.html.erb
<div class="user-posts container">
  <h3 class="user-container_heading"><%= post.title %>
    #<%= post.id %></h3>
  <p class="user-container_text"><%= truncate(post.text, :length => 50) %></p>
  <div class="user-container_misc">
    <div class="blog-btn-container">
      <%= link_to "See Post", user_post_path(user_id: post.author_id, id: post.id), class:"link" %>
      <% if can? :destroy, post %>
        <%= button_to "Delete Post", user_post_path(user_id: post.author_id, id: post.id), class:"link", method: :delete %>
      <% end %>
    </div>
    <div class="user-posts_stats">
      <p>Comments:
        <%= post.comments_counter %></p>
      <p>Likes:
        <%= post.likes_counter %></p>
      <%= render partial: "shared/like_form", locals: {user_id: post.author_id, post_id: post.id} %>
    </div>
  </div>
</div>

app/views/shared/_post_form.html.erb
<section class="new-post">
<%= render partial: "shared/back", locals: {back:user_posts_path}%>
  <h1 class="new-post_heading">Create a New Post</h1>
    <%=  form_with model:new_post, url: user_posts_url(user_id: current_user_id), class: "new-post_form" do |form| %>

      <div class= new-post_title >
        <%= form.label :title, "Title: "  %> 
        <%= form.text_field :title, autofocus: true %>
      </div>

      <div class= "new-post_desc" >
        <%= form.label :text, "Content: " %> 
        <%= form.text_area :text ,rows:5,  cols: 100 %>
      </div>

      <%= form.submit "Submit", class:"submit-post" %>
    <% end %>
</section>

app/views/shared/_user.html.erb
<div class="users-list_user">
  <div class="users-list_img">
    <img src=<%= user.photo %> alt="">
  </div>
  <div class="users-list_desc">
    <%= link_to user_path(user.id), class:"link-to_user" do %>
      <h2 class="users-list_name"><%= user.name %></h2>
    <% end %>
    <p class="users-list_posts">Number of Posts:
      <%= user.posts_counter %></p>
  </div>
</div>

app/views/users/index.html.erb
<section class="users-list">
  <%= button_to "Logout", destroy_user_session_path, class:"link", method: :delete %>
  <%= render partial: "shared/user", collection: @users %>
</section>

app/views/users/show.html.erb
<section class="user">
  <%= render partial: "shared/back", locals: {back:users_path} %>
  <%= render partial: "shared/user", locals: {user: @user_current} %>
  <div class="user-bio container">
    <h3 class="user-container_heading">Bio</h3>
    <p class="user-container_text"><%= @user_current.bio %></p>
  </div>
  <%= render partial: "shared/post", collection: @user_current.recent_posts %>
  <button class="see-all"><%= link_to "See all posts", user_posts_path(params[:id]), class:"link-to_user" %></button>
</section>